# https://taskfile.dev

version: "3"

tasks:
  default:
    desc: List all available tasks
    silent: true
    cmds:
      - task --list

  gen:
    desc: Generate the parser
    sources:
      - grammar.js
    cmds:
      - tree-sitter generate

  test:
    desc: Run the parser tests
    deps:
      - gen
    cmds:
      - tree-sitter test
