/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 5
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_marker_start = 1,
  sym_filename = 2,
  sym_marker_end = 3,
  sym__content_line = 4,
  sym_source_file = 5,
  sym_comment_section = 6,
  sym_comment_line = 7,
  sym_file_entry = 8,
  sym_file_content = 9,
  sym_file_content_line = 10,
  sym_file_marker = 11,
  aux_sym_source_file_repeat1 = 12,
  aux_sym_comment_section_repeat1 = 13,
  aux_sym_file_content_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_marker_start] = "marker_start",
  [sym_filename] = "filename",
  [sym_marker_end] = "marker_end",
  [sym__content_line] = "_content_line",
  [sym_source_file] = "source_file",
  [sym_comment_section] = "comment_section",
  [sym_comment_line] = "comment_line",
  [sym_file_entry] = "file_entry",
  [sym_file_content] = "file_content",
  [sym_file_content_line] = "file_content_line",
  [sym_file_marker] = "file_marker",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_comment_section_repeat1] = "comment_section_repeat1",
  [aux_sym_file_content_repeat1] = "file_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_marker_start] = sym_marker_start,
  [sym_filename] = sym_filename,
  [sym_marker_end] = sym_marker_end,
  [sym__content_line] = sym__content_line,
  [sym_source_file] = sym_source_file,
  [sym_comment_section] = sym_comment_section,
  [sym_comment_line] = sym_comment_line,
  [sym_file_entry] = sym_file_entry,
  [sym_file_content] = sym_file_content,
  [sym_file_content_line] = sym_file_content_line,
  [sym_file_marker] = sym_file_marker,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_comment_section_repeat1] = aux_sym_comment_section_repeat1,
  [aux_sym_file_content_repeat1] = aux_sym_file_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_marker_start] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_marker_end] = {
    .visible = true,
    .named = true,
  },
  [sym__content_line] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment_line] = {
    .visible = true,
    .named = true,
  },
  [sym_file_entry] = {
    .visible = true,
    .named = true,
  },
  [sym_file_content] = {
    .visible = true,
    .named = true,
  },
  [sym_file_content_line] = {
    .visible = true,
    .named = true,
  },
  [sym_file_marker] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_comment_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_file_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_content = 1,
  field_filename = 2,
  field_marker = 3,
  field_marker_end = 4,
  field_marker_start = 5,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_content] = "content",
  [field_filename] = "filename",
  [field_marker] = "marker",
  [field_marker_end] = "marker_end",
  [field_marker_start] = "marker_start",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_marker, 0},
  [1] =
    {field_content, 1},
    {field_marker, 0},
  [3] =
    {field_filename, 1},
    {field_marker_end, 2},
    {field_marker_start, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      if (eof) ADVANCE(1);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 2},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 4},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0, .external_lex_state = 5},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_marker_start] = ACTIONS(1),
    [sym_filename] = ACTIONS(1),
    [sym_marker_end] = ACTIONS(1),
    [sym__content_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(16),
    [sym_comment_section] = STATE(3),
    [sym_comment_line] = STATE(5),
    [sym_file_entry] = STATE(4),
    [sym_file_marker] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_comment_section_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_marker_start] = ACTIONS(5),
    [sym__content_line] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(11), 1,
      sym__content_line,
    STATE(14), 1,
      sym_file_content,
    ACTIONS(9), 2,
      sym_marker_start,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_file_content_line,
      aux_sym_file_content_repeat1,
  [15] = 4,
    ACTIONS(5), 1,
      sym_marker_start,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_file_marker,
    STATE(6), 2,
      sym_file_entry,
      aux_sym_source_file_repeat1,
  [29] = 4,
    ACTIONS(5), 1,
      sym_marker_start,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_file_marker,
    STATE(8), 2,
      sym_file_entry,
      aux_sym_source_file_repeat1,
  [43] = 3,
    ACTIONS(7), 1,
      sym__content_line,
    ACTIONS(15), 2,
      sym_marker_start,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_comment_line,
      aux_sym_comment_section_repeat1,
  [55] = 4,
    ACTIONS(5), 1,
      sym_marker_start,
    ACTIONS(17), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_file_marker,
    STATE(8), 2,
      sym_file_entry,
      aux_sym_source_file_repeat1,
  [69] = 3,
    ACTIONS(11), 1,
      sym__content_line,
    ACTIONS(19), 2,
      sym_marker_start,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_file_content_line,
      aux_sym_file_content_repeat1,
  [81] = 4,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      sym_marker_start,
    STATE(2), 1,
      sym_file_marker,
    STATE(8), 2,
      sym_file_entry,
      aux_sym_source_file_repeat1,
  [95] = 3,
    ACTIONS(28), 1,
      sym__content_line,
    ACTIONS(26), 2,
      sym_marker_start,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym_comment_line,
      aux_sym_comment_section_repeat1,
  [107] = 3,
    ACTIONS(33), 1,
      sym__content_line,
    ACTIONS(31), 2,
      sym_marker_start,
      ts_builtin_sym_end,
    STATE(10), 2,
      sym_file_content_line,
      aux_sym_file_content_repeat1,
  [119] = 1,
    ACTIONS(36), 3,
      sym_marker_start,
      sym__content_line,
      ts_builtin_sym_end,
  [125] = 1,
    ACTIONS(38), 3,
      sym_marker_start,
      sym__content_line,
      ts_builtin_sym_end,
  [131] = 1,
    ACTIONS(40), 3,
      sym_marker_start,
      sym__content_line,
      ts_builtin_sym_end,
  [137] = 1,
    ACTIONS(42), 2,
      sym_marker_start,
      ts_builtin_sym_end,
  [142] = 1,
    ACTIONS(44), 1,
      sym_filename,
  [146] = 1,
    ACTIONS(46), 1,
      ts_builtin_sym_end,
  [150] = 1,
    ACTIONS(48), 1,
      sym_marker_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 29,
  [SMALL_STATE(5)] = 43,
  [SMALL_STATE(6)] = 55,
  [SMALL_STATE(7)] = 69,
  [SMALL_STATE(8)] = 81,
  [SMALL_STATE(9)] = 95,
  [SMALL_STATE(10)] = 107,
  [SMALL_STATE(11)] = 119,
  [SMALL_STATE(12)] = 125,
  [SMALL_STATE(13)] = 131,
  [SMALL_STATE(14)] = 137,
  [SMALL_STATE(15)] = 142,
  [SMALL_STATE(16)] = 146,
  [SMALL_STATE(17)] = 150,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 1, 0, 1),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_section, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_content, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_comment_section_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_comment_section_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_file_content_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_file_content_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment_line, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_content_line, 1, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_marker, 3, 0, 3),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_entry, 2, 0, 2),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [46] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_marker_start = 0,
  ts_external_token_filename = 1,
  ts_external_token_marker_end = 2,
  ts_external_token__content_line = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_marker_start] = sym_marker_start,
  [ts_external_token_filename] = sym_filename,
  [ts_external_token_marker_end] = sym_marker_end,
  [ts_external_token__content_line] = sym__content_line,
};

static const bool ts_external_scanner_states[6][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_marker_start] = true,
    [ts_external_token_filename] = true,
    [ts_external_token_marker_end] = true,
    [ts_external_token__content_line] = true,
  },
  [2] = {
    [ts_external_token_marker_start] = true,
    [ts_external_token__content_line] = true,
  },
  [3] = {
    [ts_external_token_marker_start] = true,
  },
  [4] = {
    [ts_external_token_filename] = true,
  },
  [5] = {
    [ts_external_token_marker_end] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_txtar_external_scanner_create(void);
void tree_sitter_txtar_external_scanner_destroy(void *);
bool tree_sitter_txtar_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_txtar_external_scanner_serialize(void *, char *);
void tree_sitter_txtar_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_txtar(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_txtar_external_scanner_create,
      tree_sitter_txtar_external_scanner_destroy,
      tree_sitter_txtar_external_scanner_scan,
      tree_sitter_txtar_external_scanner_serialize,
      tree_sitter_txtar_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "txtar",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
